Repository openstack-k8s-operators/mariadb-operator, pull requests merged in 2022-08, with the labels that each got.

#29 Add CI folks in OWNERS file
  OWNERS
Labels: lgtm

#27 Create separate module for API structs
  .github/workflows/build-mariadb-operator.yaml
  .github/workflows/golangci-lint.yaml
  api/go.mod
  api/go.sum
  go.mod
Labels: approved

#32 [Controller] Use common.GetLabels instead of mariadb.GetLabels
  controllers/mariadb_controller.go
  controllers/mariadbdatabase_controller.go
  go.mod
  go.sum
  pkg/const.go
  pkg/database.go
Labels: lgtm, approved, ok-to-test
