Repository openstack-k8s-operators/mariadb-operator, pull requests merged in 2023-01, with the labels that each got.

#48 Add simple kuttl tests for mariadb
  kuttl-test.yaml
  tests/kuttl/tests/mariadb_deploy/01-assert.yaml
  tests/kuttl/tests/mariadb_deploy/01-deploy-mariadb.yaml
Labels: lgtm, approved, needs-ok-to-test

#49 Move deployment assert to a common folder
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/mariadb_deploy/01-assert.yaml
Labels: lgtm, approved, ok-to-test

#51 Replace remaining direct reference to password
  templates/mariadb/bin/mariadb_init.sh
Labels: lgtm, approved

#54 Provide additional label to identify the operator
  config/manager/manager.yaml
Labels: lgtm, approved

#53 Add pre-commit config
  .github/create_bundle.sh
  .github/create_opm_index.sh
  .pre-commit-config.yaml
  README.md
  api/v1beta1/conditions.go
  api/v1beta1/groupversion_info.go
  config/samples/mariadb_v1beta1_mariadb.yaml
  hack/boilerplate.go.txt
  templates/database.sh
  templates/delete_database.sh
Labels: lgtm, approved

#55 Add renovate.json / Remove dependabot.yml
  .github/dependabot.yml
  renovate.json
Labels: lgtm, approved
