Repository openstack-k8s-operators/mariadb-operator, pull requests merged in 2023-05, with the labels that each got.

#104 normalize DEFAULT_IMAGE and kustomization.yaml
  Makefile
  config/manager/kustomization.yaml
Labels: lgtm, approved, ok-to-test

#106 github workflowupdates for master to main update
  .github/workflows/build-mariadb-operator.yaml
Labels: approved

#107 Controller manager label finalization
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
Labels: lgtm, approved
